### PR TITLE
Remove deprecated gulp-util

### PR DESCRIPTION
**Pull request by a-golovanov**
For details see https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### CODE REVIEW

**Comment by anseki** [comment]
Hi @a-golovanov, thank you for the PR. 😄 
It was merged manually.

**Comment by agurtovoy** [comment]
@anseki Any reason not to accept the tests that came with this PR?

**Comment by anseki** [comment]
Hi @agurtovoy,

Yes, it seems that the tests almost never test the gulp-confirm, and it tests `plugin-error` and `fancy-log` only.
That is, the tests only confirm that gulp-confirm calls `plugin-error` and `fancy-log`. Also, it doesn't test a case that gulp-confirm should not call those.

Tests for the gulp-confirm should test the gulp-confirm's behavior such as [`input`](https://github.com/anseki/gulp-confirm#input) option. gulp-confirm is being tested another way now because that requires keyboard operations. It simulates readline interfaces.

**Comment by agurtovoy** [comment]
> it seems that the tests almost never test the gulp-confirm, and it tests plugin-error and fancy-log only.

They test error handling, which is a part of gulp-confirm's contract, no? I'm glad to hear that gulp-confirm is being tested with simulated keyboard input, but IMHO that doesn't negate the need for tests along the lines of what's in this PR.

Just my 2c.

**Comment by anseki** [comment]
To test the error handling, at least, it should confirm both a case that the program throws an error and a case that the program doesn't throw an error.
Otherwise, the program might always throw an error by another problem.
In other words, it should confirm why the program throw an error.
Anyhow I thank for @a-golovanov.

**Pull request closed without merging**
